### ISSUE TITLE
Prepare bash script with installer of dependent packages

### ISSUE THREAD

**Issue by grzanka** [grzanka/cookiecutter-pip-docker-versioneer#20]
numpy and scipy should be installed from system repositories, not using pip

**Comment by ant6** [comment]
What about other (probably) required packages e.g. fortran?
According to my previous tests with travis those are required:
```
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
```
